version: "3"
name: "coderic"
services:
  ruben: 
    image: httpd:latest
    stdin_open: true
    tty: true
    domainname: coderic.net
##    hostname: ruben
    privileged: true
    networks:
      - mynetwork
    deploy:
      mode: replicated
      replicas: 100
      update_config:
        parallelism: 0
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
  juda: 
    image: haproxy:lts
    stdin_open: true
    tty: true
    domainname: coderic.net
    hostname: juda
    privileged: true
    networks:
      - mynetwork
    ports:
      - 80:80
      - 8404:8404
    volumes:
      -  ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - ruben
    depends_on:
      - ruben
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    deploy:
      update_config:
        parallelism: 0
        delay: 10s
      restart_policy:
        condition: on-failure

##  neftali: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: neftali
##    privileged: true
##    networks:
##      - host
##  gad: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: gad
##    privileged: true
##    networks:
##      - host
##  aser: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: aser
##    privileged: true
##    networks:
##      - host
##  isacar: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: isacar
##    privileged: true
##    networks:
##      - host
##  zabulon: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: zabulon
##    privileged: true
##    networks:
##      - host
##  jose: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: jose
##    privileged: true
##    networks:
##      - host
##  manases: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: manases
##    privileged: true
##    networks:
##      - host
##  efrain: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: efrain
##    privileged: true
##    networks:
##      - host
##  benjamin: 
##    image: fedora
##    stdin_open: true
##    tty: true
##    domainname: coderic.net
##    hostname: benjamin
##    privileged: true
##    networks:
##      - host
networks:
  mynetwork:
    driver: bridge
    external: true
